# Generated by Django 4.0.1 on 2022-01-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karty_Graficzne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marka', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('VRAM', models.IntegerField(max_length=5)),
                ('avgCena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('czestotliwosc', models.IntegerField(max_length=5)),
            ],
        ),
    ]
